apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-1
  namespace: project-1  # Ensure this namespace is consistent across all files
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project-1
  
  template:
    metadata:
      labels:
        app: project-1
    
    spec:
      containers:
      - name: project-1
  
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config-volume
        configMap:
          name: project-1-config
      
