apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-config
  namespace: demo-config  # Ensure this namespace is consistent across all files
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-config
  template:
    metadata:
      labels:
        app: demo-config
    spec:
      containers:
      - name: demo-config
        image: nginx
        ports:
        - containerPort: 81
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config-volume
        configMap:
          name: demo-config
