apiVersion: v1
kind: Service
metadata:
  name: demo-config
  namespace: demo-config
spec:
  selector:
    app: demo-config
  ports:
    - protocol: TCP
      port: 81
      targetPort: 81
  type: LoadBalancer

