apiVersion: v1
kind: Service
metadata:
  name: project-1
  namespace: project-1
spec:
  selector:
    app: project-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

